name: MCLACore
version: 1.0
main: me.notdew.com.mclacore.MCLACore
author: NotDew
api-version: 1.16
description: MCLA Network Core Plugin.
commands:
  score:
    usage: /<command>
  hitlists:
    usage: /<command>
  getball:
    usage: /<command>
  removeball:
    usage: /<command>